### ISSUE TITLE
Compile error on JavaStocks.java

### ISSUE THREAD

**Issue by jomach** [sryza/spark-ts-examples#1]
Hi @sryza so the project does not compile :) 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spark-ts-examples: Compilation failure: Compilation failure:
[ERROR] /Users/jorge/Downloads/spark-ts-examples/jvm/src/main/java/com/cloudera/tsexamples/JavaStocks.java:[67,61] cannot find symbol
[ERROR] symbol:   method javaTimeSeriesRDDFromObservations(com.cloudera.sparkts.DateTimeIndex,org.apache.spark.sql.DataFrame,java.lang.String,java.lang.String,java.lang.String)
[ERROR] location: class com.cloudera.sparkts.api.java.JavaTimeSeriesRDDFactory
[ERROR] /Users/jorge/Downloads/spark-ts-examples/jvm/src/main/java/com/cloudera/tsexamples/JavaStocks.java:[89,42] cannot find symbol
[ERROR] symbol:   variable swap
[ERROR] location: variable s of type scala.Tuple2<java.lang.String,java.lang.Double>
[ERROR] /Users/jorge/Downloads/spark-ts-examples/jvm/src/main/java/com/cloudera/tsexamples/JavaStocks.java:[89,48] cannot find symbol
[ERROR] symbol:   variable min
[ERROR] location: class org.apache.spark.api.java.JavaRDD<java.lang.Object>
[ERROR] /Users/jorge/Downloads/spark-ts-examples/jvm/src/main/java/com/cloudera/tsexamples/JavaStocks.java:[90,42] cannot find symbol
[ERROR] symbol:   variable swap
[ERROR] location: variable s of type scala.Tuple2<java.lang.String,java.lang.Double>
[ERROR] /Users/jorge/Downloads/spark-ts-examples/jvm/src/main/java/com/cloudera/tsexamples/JavaStocks.java:[90,48] cannot find symbol
[ERROR] symbol:   variable max
[ERROR] location: class org.apache.spark.api.java.JavaRDD<java.lang.Object>

You have missing some ; and I delete some  stuff on my for.

**Comment by sryza** [comment]
Hi @jomach.  The example had been incomplete, but I just updated it to make it compile.  Let me know if it still doesn't work for you.
